LOAD DATA LOCAL INFILE "data/state.csv" INTO TABLE State FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/city.csv" INTO TABLE City FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/climate.csv" INTO TABLE Climate FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/viewpoint.csv" INTO TABLE Viewpoint FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/population.csv" INTO TABLE Population FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/economics.csv" INTO TABLE Economics FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/airport.csv" INTO TABLE Airport FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/college.csv" INTO TABLE College FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/museum.csv" INTO TABLE Museum FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "data/sportteam.csv" INTO TABLE Sportteam FIELDS TERMINATED BY ',';